module(name = "devtools-ui", version = "1.0")

bazel_dep(name = "rules_player")

archive_override(
    module_name = "rules_player",
    strip_prefix = "rules_player-2.6.6",
    urls = ["https://github.com/player-ui/rules_player/archive/refs/tags/v2.6.6.tar.gz"],
)

bazel_dep(name = "aspect_bazel_lib", version = "2.22.5")
bazel_dep(name = "aspect_rules_js", version = "2.3.8")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "rules_pkg", version = "1.1.0")
bazel_dep(name = "aspect_rules_ts", version = "3.8.10")
bazel_dep(name = "aspect_rules_swc", version = "2.7.5")
bazel_dep(name = "rules_cc", version = "0.2.18")

####### Node.js version #########
bazel_dep(name = "rules_nodejs", version = "6.7.5")
node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node")
node.toolchain(node_version = "18.18.0")
#################################

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")

npm.npm_translate_lock(
    name = "npm",
    pnpm_lock = "//:pnpm-lock.yaml",
    data = [
        "//:package.json",
    ],
    npm_package_target_name = "{dirname}",
    npmrc = "//:.npmrc",
    verify_node_modules_ignored = "//:.bazelignore",
)

use_repo(npm, "npm")

rules_ts_ext = use_extension(
    "@aspect_rules_ts//ts:extensions.bzl",
    "ext",
    dev_dependency = True,
)

rules_ts_ext.deps(ts_version = "4.8.4")

use_repo(rules_ts_ext, "npm_typescript")
